export const ModelNameConstant = {
    City: 'Countries.CityDTO',
    Country: 'Countries.CountryDTO',
    Customer: 'Customers.CustomerDTO',
    CustomerContact: 'Customers.CustomerContactDTO',
    CustomerType: 'Customers.CustomerTypeDTO',
    LostCustomer: 'Customers.LostCustomerDTO',
    TypeCustomerMarket: 'Customers.TypeCustomerMarketDTO',
    Claim: 'dbo.ClaimDTO',
    Role: 'dbo.RoleDTO',
    RoleClaims: 'dbo.RoleClaimsDTO',
    UserClaims: 'dbo.UserClaimsDTO',
    UserRoles: 'dbo.UserRolesDTO',
    Users: 'dbo.UsersDTO',
    Distributor: 'Distributors.DistributorDTO',
    DistributorContact: 'Distributors.DistributorContactDTO',
    DocumentType: 'Distributors.DocumentTypeDTO',
    Installation: 'Installations.InstallationDTO',
    InstallationDetails: 'Installations.InstallationDetailsDTO',
    InstallationStatus: 'Installations.InstallationStatusDTO',
    ReceptionContact: 'Installations.ReceptionContactDTO',
    TypeRequest: 'Installations.TypeRequestDTO',
    Commentary: 'Opportunities.CommentaryDTO',
    Opportunity: 'Opportunities.OpportunityDTO',
    OpportunityStatus: 'Opportunities.OpportunityStatusDTO',
}

export const ListNameConstant = {
    City: 'city',
    Country: 'country',
    Customer: 'customer',
    CustomerContact: 'customer contact',
    CustomerType: 'customer type',
    LostCustomer: 'lost customer',
    TypeCustomerMarket: 'type customer market',
    Claim: 'claim',
    Role: 'role',
    RoleClaims: 'role claims',
    UserClaims: 'user claims',
    UserRoles: 'user roles',
    Users: 'users',
    Distributor: 'distributor',
    DistributorContact: 'distributor contact',
    DocumentType: 'document type',
    Installation: 'installation',
    InstallationDetails: 'installation details',
    InstallationStatus: 'installation status',
    ReceptionContact: 'reception contact',
    TypeRequest: 'type request',
    Commentary: 'commentary',
    Opportunity: 'opportunity',
    OpportunityStatus: 'opportunity status',
}